# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'prometheus-cluster'
    replica: 'prometheus-01'

# 告警规则文件
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter 监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'localhost:9100'
    scrape_interval: 15s
    metrics_path: /metrics

  # MySQL Exporter 监控
  - job_name: 'mysql-exporter'
    static_configs:
      - targets:
        - 'localhost:9104'
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana 监控
  - job_name: 'grafana'
    static_configs:
      - targets:
        - 'localhost:3000'
    scrape_interval: 30s
    metrics_path: /metrics

  # Loki 监控
  - job_name: 'loki'
    static_configs:
      - targets:
        - 'localhost:3100'
    scrape_interval: 30s
    metrics_path: /metrics

  # Tempo 监控
  - job_name: 'tempo'
    static_configs:
      - targets:
        - 'localhost:3200'
    scrape_interval: 30s
    metrics_path: /metrics

  # 应用程序监控示例
  # - job_name: 'my-app'
  #   static_configs:
  #     - targets: ['localhost:8080']
  #   scrape_interval: 15s
  #   metrics_path: /actuator/prometheus

# 远程写入配置（可选）
# remote_write:
#   - url: "http://remote-prometheus:9090/api/v1/write"

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-prometheus:9090/api/v1/read" 